# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

Answer:

In [7]:
import numpy as np
from numpy import random
import math

matriks4x4 = np.zeros((4,4))
print("Create 4x4 Matrix with zero values")
print(matriks4x4)
print("-----------------------------------")
print("Change values ranging from 0 to 3")
matriks4x4 += np.arange(4)
print(matriks4x4)

Create 4x4 Matrix with zero values
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------
Change values ranging from 0 to 3
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

Answer

In [8]:
matriks = np.arange(0, 16).reshape(4,4)
print("Original Matriks 4x4:")
print(matriks)
matriks = np.hsplit(matriks,2)
print("-----------------------------------")
print("Split into 2 arrays:")
print(" ")
print("Data split 1")
print(matriks[0])
print(" ")
print("Data split 2")
print(matriks[1])

Original Matriks 4x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------------------------------
Split into 2 arrays:
 
Data split 1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
 
Data split 2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
3. Soal tambahan:

Misalkan kita memiliki data array seperti berikut ini :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
Tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima ? 

jika dilihat dari data, output yang diinginkan : 2, 3, 7, 11, 13, 17, 19, 23

Answer 1:

In [10]:
def is_prime(n):
    if n % 2 == 0 and n > 2 or (n == 0 or n == 1) : 
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

array = np.arange(1, 26).reshape(5,5)
foo = np.vectorize(is_prime)
pbools = foo(array)
primes = np.extract(pbools, array)


print("Array yang dimiliki (sebelum difilter):") 
print(array) 
print("----------------------------") 
print("Filtering mendapatkan bilangan prima:") 
print(primes)

Array yang dimiliki (sebelum difilter):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
----------------------------
Filtering mendapatkan bilangan prima:
[ 2  3  5  7 11 13 17 19 23]


Answer 2:

In [11]:
def isPrime(n):
    if n == 1:
        return False
    if n == 2:
        return True
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

In [12]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
prima = []
for line in arr:
    for item in line:
        if isPrime(item):
            prima.append(item)
            
arrPrime = np.array(prima)
arrPrime

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [19]:
arrPrime2 = np.array([item for item in arr.flatten() if isPrime(item)])
arrPrime2

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])